[project]
name = "ko-agentbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
<<<<<<< HEAD
    "python-dotenv>=1.0.0",
=======
    "dotenv>=0.9.9",
    "ipykernel>=6.30.1",
>>>>>>> e899c6aa717f6ad4a22e0f4f343ce676421236b0
    "litellm>=1.77.0",
    "requests>=2.32.5",
    "transformers>=4.56.1",
    "google-auth>=2.35.0",
    "google-cloud-aiplatform>=1.71.1",
    "jwt>=1.4.0",
]
